spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meme-ministry?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  error:
    include-message: always
  tomcat:
    connection-timeout: 60000