spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meme-ministry?createDatabaseIfNotExist=true
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
        current_session_context_class: thread
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

server:
  error:
    include-message: always